- name: check variables are defined
  assert:
    that:
      - cluster_name is defined

- name: Check if kubeadm is present at /usr/local/bin/kubeadm
  stat:
    path: /usr/local/bin/kubeadm
  register: kubeadm_stat

- name: Fail this host because kubeadm is already installed
  fail:
    msg: "kubeadm is already installed at /usr/local/bin/kubeadm"
  when: kubeadm_stat.stat.exists

- name: Get latest kubeadm release version
  uri:
    url: "{{ archive_root_url }}/{{ cluster_name }}-release.txt"
    return_content: true
  register: release_version

- name: get architecture
  command: dpkg --print-architecture
  register: architecture

- name: Download kubeadm tar.gz
  get_url:
    url: "{{ archive_root_url }}/kubeadm-{{ release_version.content | trim }}-{{ architecture.stdout }}.tar.gz"
    dest: /tmp/kubeadm.tar.gz

- name: Extract kubeadm archive
  unarchive:
    src: /tmp/kubeadm.tar.gz
    dest: /tmp
    remote_src: true

- name: Run install-dependencies.sh
  command: bash install-dependencies.sh
  args:
    chdir: /tmp

- name: Clean up kubeadm archive
  file:
    path: /tmp/kubeadm.tar.gz
    state: absent