- name: check variables are defined
  assert:
    that:
      - cluster_name is defined

- name: Check for kubeadm installation
  command: which kubeadm
  register: kubeadm_check
  ignore_errors: yes

- name: Fail if kubeadm is already installed
  fail:
    msg: "kubeadm is already installed at {{ kubeadm_check.stdout }}"
  when: kubeadm_check.rc == 0

- name: Get latest kubeadm release version
  uri:
    url: "{{ archive_root_url }}/{{ cluster_name }}release.txt"
    return_content: true
  register: release_version

- name: get architecture
  shell:
    cmd: "dpkg --print-architecture"
  register: architecture

- name: Download kubeadm tar.gz
  get_url:
    url: "{{ archive_root_url }}/kubeadm-{{ release_version.content | trim }}-{{ architecture.stdout }}.tar.gz"
    dest: /tmp/kubeadm.tar.gz

- name: Extract kubeadm archive
  unarchive:
    src: /tmp/kubeadm.tar.gz
    dest: /tmp
    remote_src: true

- name: Run install-dependencies.sh
  command: bash install-dependencies.sh
  args:
    chdir: /tmp

- name: Clean up kubeadm archive
  file:
    path: /tmp/kubeadm.tar.gz
    state: absent